name: Kacper Bojakowski
title: HARMAN TARGET EQUALIZATION
description: Guide on how to improve the sound of your headphones for free
remote_theme: KomunikacjaTechnicznaVistula/just-the-docs

color_scheme: vistula

#logo: "/assets/images/Morris_badge.png"

aux_links:
  "Source repository on GitHub":
    - "//github.com/KomunikacjaTechnicznaVistula/kacper-bojakowski"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: This document was created as a part of my technical writing training at Vistula University in Warsaw. 
